// src/components/configuration/camera/CameraConfig.vue
<template>
  <b-section>
    <b-title>Camera</b-title>
    <hr />

    <b-field>
      <b-label>Web Video Server Port</b-label>
      <input v-model="currentIP" class="input is-small" placeholder="8080" />
    </b-field>

    <input-with-button
      ref="camToAdd"
      v-model="cameraNameToAdd"
      label="Add Camera"
      button-text="Add"
      @click="addCamera"
    />

    <diV class="cameras">
      <div v-for="(camera, key) in cameras" :key="key">
        <camera-card class="camera" :title="key" :camera-name="key" />
      </div>
    </diV>
  </b-section>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'

import CameraCard from './CameraCard.vue'
import { InputWithButton } from '@/components/ui'

import { cameraModule } from '@/store'
import { CameraType } from '@/store/modules/camera.types'

@Component({ components: { CameraCard, InputWithButton } })
export default class CameraConfig extends Vue {
  cameraNameToAdd = ''

  get cameras() {
    return cameraModule.cameras
  }

  get currentIP() {
    return cameraModule.videoServerPort
  }

  set currentIP(value: string) {
    cameraModule.setVideoServerPort(value)
  }

  addCamera() {
    cameraModule.addCamera({
      cameraName: this.cameraNameToAdd,
      options: { type: CameraType.MJPEG, topic: '/' },
    })
    this.cameraNameToAdd = ''
  }
}
</script>

<style lang="scss" scoped>
.cameras {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-gap: 5px;
}
</style>

// src/components/pages/Config/pages/CameraConfig/CameraConfig.tsx
import React, { ChangeEvent, FC } from 'react'
import { useDispatch } from 'react-redux'
import { CameraType } from 'store/modules/feed/@types'
import { useSelector } from 'utils/hooks/typedUseSelector'
import { CameraConfigWrapper } from 'components/pages/Config/pages/CameraConfig/CameraConfig.styles'
import { feedSlice } from 'store/modules/feed/reducer'
import { LabeledInput } from 'components/common/LabeledInput'
import { rosSlice } from 'store/modules/ros/reducer'
import { Table } from './Table'
import { Button } from 'components/common/Button'
import { SectionTitle } from 'components/pages/Config/styles'

const VideoServerPortConfig: FC = () => {
  const dispatch = useDispatch()
  const videoServerPort = useSelector(state => state.ros.videoServerPort)

  const updateVideoServerPort = (e: ChangeEvent<HTMLInputElement>) =>
    dispatch(rosSlice.actions.setVideoServerPort(e.target.value))

  return (
    <>
      <LabeledInput
        label="Port"
        value={videoServerPort}
        onChange={updateVideoServerPort}
      />
    </>
  )
}

const AddCamera = () => {
  const dispatch = useDispatch()

  const addFeed = () =>
    dispatch(
      feedSlice.actions.addCamera({
        name: '',
        topic: '',
        type: CameraType.MJPEG,
      })
    )

  return <Button onClick={addFeed}>Add New Camera</Button>
}

const VideoServerSection = () => (
  <>
    <SectionTitle>Video Server Settings</SectionTitle>
    <VideoServerPortConfig />
  </>
)

const CameraTableSection = () => (
  <>
    <SectionTitle>Cameras</SectionTitle>
    <AddCamera />
    <Table />
  </>
)

export const CameraConfig: FC = () => {
  return (
    <CameraConfigWrapper>
      <VideoServerSection />
      <CameraTableSection />
    </CameraConfigWrapper>
  )
}
